name: test ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      ssh_key: ${{ secrets.SSH_KEY }}

    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p ~/.ssh
    - run: echo $ssh_key | base64 -d > ~/.ssh/id_rsa
    - run: chmod 0600 ~/.ssh/id_rsa
    - run: ssh -o StrictHostKeyChecking=no bdb2c2023q4_guest_3@brain-client.bigdatateam.org "mkdir roman && touch task41.txt"
    - run: python3 test.py
    - run: echo "OK"
